name: Build BennuGD for WebOS

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-webos:
    runs-on: ubuntu-latest

    env:
      WEBOS_SDK_URL: https://github.com/humbertodias/native-toolchain/releases/download/webos-d7ed7ee.8/arm-webos-linux-gnueabi_sdk-buildroot_linux-x86_64.tar.bz2
      WEBOS_SDK_DIR: ${{ github.workspace }}/arm-webos-linux-gnueabi_sdk-buildroot

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          set -e
          sudo apt update -y
          sudo apt install -y wget bzip2 cmake file

      - name: Download and extract WebOS SDK
        run: |
          set -e
          wget $WEBOS_SDK_URL
          tar xvfj $(basename $WEBOS_SDK_URL)
          rm $(basename $WEBOS_SDK_URL)

      - name: Relocate WebOS SDK and setup toolchain
        run: |
          set -e
          cd $WEBOS_SDK_DIR
          ./relocate-sdk.sh
          cd bin
          unlink arm-webos-linux-gnueabi-gcc || true
          unlink arm-webos-linux-gnueabi-g++ || true
          ln -s arm-webos-linux-gnueabi-gcc.br_real arm-webos-linux-gnueabi-gcc
          ln -s arm-webos-linux-gnueabi-g++.br_real arm-webos-linux-gnueabi-g++

      - name: Build BennuGD
        run: |
          set -e
          export WEBOS_SDK_BUILDROOT=$WEBOS_SDK_DIR
          cmake -B build -DCMAKE_TOOLCHAIN_FILE=$WEBOS_SDK_BUILDROOT/share/buildroot/toolchainfile.cmake
          cmake --build build
          file build/bennugd_libretro.so

      - name: Upload files
        uses: actions/upload-artifact@v5
        with:
          name: bennugd-libretro-webos
          path: |
            build/lib/*.a
            build/bennugd_libretro.so
